### ISSUE TITLE
Issues on mac

### ISSUE THREAD

**Issue by Zackio** [apiad/sublime-browser-integration#4]
Any one got this working on mac? I get this error, it says i need chromedriver in the path, i have it installed and available in the terminal?

[Start] Browser Integration :: Opening new Chrome instance.
Exception in thread Thread-76:
Traceback (most recent call last):
  File "selenium.webdriver.chrome.service in /Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Browser Integration.sublime-package", line 63, in start
  File "X/subprocess.py", line 818, in **init**
  File "X/subprocess.py", line 1416, in _execute_child
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "X/threading.py", line 596, in run
  File "browser_integration_launch in /Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Browser Integration.sublime-package", line 28, in open_browser
  File "browser in /Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Browser Integration.sublime-package", line 27, in connect
  File "selenium.webdriver.chrome.webdriver in /Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Browser Integration.sublime-package", line 59, in __init__
  File "selenium.webdriver.chrome.service in /Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Browser Integration.sublime-package", line 68, in start
selenium.common.exceptions.WebDriverException: Message: 'ChromeDriver executable needs to be available in the path.                 Please download from http://chromedriver.storage.googleapis.com/index.html                and read up at http://code.google.com/p/selenium/wiki/ChromeDriver' 

[End] Browser Integration :: Opening new Chrome instance.

**Comment by apiad** [comment]
Hi, thanks for sharing. I've been out of this project for some time, which is why I've taken my time to reply. I'm deeply sorry for that.

The plugin doesn't actually uses the system `chromedriver`, instead it attempts to download one from http://sublime.apiad.net. I did this to avoid incompatibilities and ensure that the plugin always has a version of `chromedriver` that I'm sure is compatible with the embedded `selenium` library. You are getting a `NotADirectory` error, so my guess is that the plugin was unable to download `chromedriver` into its desired location because it is compacted as a `.sublime-plugin` file. I though I had this fixed by now, evidently it didn't. 

I'll try to look at it as soon as possible. In the meantime, have you tried it with Firefox? 

I'm now working on a complete redesign, removing `selenium` and all `chromedriver` issues in a favor  of a proxy-based architecture. Hope this solves the many headaches I'm getting with `chromedriver`.

Once again, thanks a lot for trying and sharing!
