### ISSUE TITLE
Launching Firefox

### ISSUE THREAD

**Issue by gkrzyminski** [apiad/sublime-browser-integration#6]
Any idea, why do I get this error, while trying to launch Firefox?

```
[Start] Browser Integration :: Opening new Firefox instance.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "browser_integration_launch in C:\Users\grzegorz.krzyminski\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Integration.sublime-package", line 28, in open_browser
  File "browser in C:\Users\grzegorz.krzyminski\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Integration.sublime-package", line 29, in connect
  File "selenium.webdriver.firefox.webdriver in C:\Users\grzegorz.krzyminski\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Integration.sublime-package", line 43, in __init__
  File "C:\Users\grzegorz.krzyminski\AppData\Roaming\Sublime Text 3\Installed Packages\Browser Integration.sublime-package\selenium\webdriver\firefox\firefox_profile.py", line 58, in __init__
    WEBDRIVER_PREFERENCES)) as default_prefs:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\grzegorz.krzyminski\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\Browser Integration.sublime-package\\selenium\\webdriver\\firefox\\webdriver_prefs.json'

[End] Browser Integration :: Opening new Firefox instance.
```

**Comment by apiad** [comment]
Hi,
I haven't looked at this plugin for a while. Firefox support has never
been completed, and probably with newer versions of either Firefox or
Selenium, or even Sublime, things will break. Let me take a deeper
look and I'll get back to you as soon as I have an answer.

Thanks for sharing!

Ale.
