### ISSUE TITLE
"ChromeDriver executable needs to be available in the path" on Ubuntu / ST3

### ISSUE THREAD

**Issue by jleskovar** [apiad/sublime-browser-integration#8]
Constantly get the following error when attempting to launch chrome:

```
[Start] Browser Integration :: Opening new Chrome instance.
Exception in thread Thread-10:
Traceback (most recent call last):
  File "selenium.webdriver.chrome.service in /home/james/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 63, in start
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "browser_integration_launch in /home/james/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 28, in open_browser
  File "browser in /home/james/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 27, in connect
  File "selenium.webdriver.chrome.webdriver in /home/james/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 59, in __init__
  File "selenium.webdriver.chrome.service in /home/james/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 68, in start
selenium.common.exceptions.WebDriverException: Message: 'ChromeDriver executable needs to be available in the path.                 Please download from http://chromedriver.storage.googleapis.com/index.html                and read up at http://code.google.com/p/selenium/wiki/ChromeDriver' 
```
- Installed on Sublime Text 3, via Package Control
- I have chromedriver in the following directories:
  - /usr/bin
  - ~/.config/sublime-text-3
  - ~/.config/sublime-text-3/Installed Packages
  - ~/.config/sublime-text-3/Packages

**Comment by maqboolkhan** [comment]
+1

**Comment by jleskovar** [comment]
Small update on this issue -  sorry for not updating sooner. You need to install the package manually - not via Package Control. PC installs the package as a tarball, which results in the errors you see above. Installing manually as a directory and placing chromedriver in the package directory should do the trick.

**Comment by apiad** [comment]
Hi,
Sorry for taking so long. I'm not actively developing on this line anymore, because I don't think I can deal with selenium vs. chrome updates fast enough. So I'm completely changing the architecture, to dump selenium completely in favor of using a proxy + socket.io, which would make the plugin completely self-contained and automatically compatible with any browser, and all the time I devote to this plugin is on this new development line. 
Thanks @jleskovar for the tip for manually fixing it. I hope to have the renewed version ready for new year!
